### ISSUE TITLE
SCBank cannot be opened

### ISSUE THREAD

**Issue by Chromowolf** [armoha/SCBank#1]
I double-clicked the exe file:
![image](https://user-images.githubusercontent.com/37732663/112169011-c6ff4580-8c2c-11eb-8631-c3ad38eb4ef4.png)

And then the following window just flashed once and disappeared immediately:
![image](https://user-images.githubusercontent.com/37732663/112169267-03cb3c80-8c2d-11eb-9d9d-ab010e7bc453.png)
![image](https://user-images.githubusercontent.com/37732663/112169476-2fe6bd80-8c2d-11eb-9ee6-e6438e0dd593.png)

I read edac/77960 and edac/77992 and there is no instruction on this

**Comment by armoha** [comment]
Use https://github.com/armoha/dis-zero instead.

**Comment by Chromowolf** [comment]
Thank you. I downloaded dis-zero and don't know what it can help on EUD game saving. Is there any instruction on how to save game in EUD maps?

**Comment by armoha** [comment]
> I downloaded dis-zero and don't know what it can help on EUD game saving

SCBank hasn't implemented save game yet and prolly won't. I'm thinking of making new language and adding chat-based saveload system like WC3 maps do.
> Is there any instruction on how to save game in EUD maps?

There is no save game support like original SC but similar to SC2 bank/WC save engine (saveload user data). Look for SCArchive or SCDB.

**Comment by Chromowolf** [comment]
Thx. Got it
